"use client";

import React from "react";
import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Heart, Activity, Brain, Zap, ShieldCheck, RotateCcw } from "lucide-react";
import Link from "next/link";

interface ResultData {
  heartRate: number;
  spo2: number;
  stress: string;
  wellnessScore: number;
  confidence: number;
}

const ResultsScreen = ({ data }: { data: ResultData }) => {
  const resultCards = [
    {
      title: "Heart Rate",
      value: `${data.heartRate}`,
      unit: "BPM",
      icon: <Heart className="text-red-500" />,
      color: "text-red-500",
    },
    {
      title: "SpO2",
      value: `${data.spo2}`,
      unit: "%",
      icon: <Activity className="text-blue-400" />,
      color: "text-blue-400",
    },
    {
      title: "Stress Level",
      value: data.stress,
      unit: "",
      icon: <Brain className="text-purple-400" />,
      color: "text-purple-400",
    },
    {
      title: "Confidence",
      value: `${data.confidence}`,
      unit: "%",
      icon: <ShieldCheck className="text-emerald-400" />,
      color: "text-emerald-400",
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-12"
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-6">
          Scan Complete
        </div>
        <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">Your Wellness Report</h2>
        <p className="text-white/50">Generated by VitalScan AI v2.0</p>
      </motion.div>

      {/* Wellness Score Large Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2 }}
        className="mb-8"
      >
        <Card className="bg-gradient-to-br from-blue-600/20 to-purple-600/20 border-white/10 p-8 text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Zap className="w-24 h-24 text-white" />
          </div>
          <p className="text-white/60 font-medium uppercase tracking-widest text-sm mb-2">Overall Wellness Score</p>
          <div className="text-7xl font-black text-white mb-4">{data.wellnessScore}</div>
          <div className="w-full max-w-md mx-auto h-2 bg-white/5 rounded-full overflow-hidden">
            <motion.div 
              initial={{ width: 0 }}
              animate={{ width: `${data.wellnessScore}%` }}
              transition={{ duration: 1.5, delay: 0.5 }}
              className="h-full bg-gradient-to-r from-blue-500 to-purple-500" 
            />
          </div>
          <p className="mt-4 text-emerald-400 font-medium text-sm">Optimal Performance Range</p>
        </Card>
      </motion.div>

      {/* Grid of Results */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-12">
        {resultCards.map((card, i) => (
          <motion.div
            key={card.title}
            initial={{ opacity: 0, x: i % 2 === 0 ? -20 : 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 + i * 0.1 }}
          >
            <Card className="bg-white/5 border-white/10 p-6 flex items-center justify-between group hover:bg-white/[0.08] transition-colors">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl bg-black/40 border border-white/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                  {card.icon}
                </div>
                <div>
                  <p className="text-xs text-white/40 font-bold uppercase">{card.title}</p>
                  <div className="flex items-baseline gap-1">
                    <span className={`text-2xl font-bold text-white`}>{card.value}</span>
                    <span className="text-sm text-white/40">{card.unit}</span>
                  </div>
                </div>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>

      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <Button variant="premium" size="lg" className="rounded-full px-12" asChild>
          <Link href="/">Save to Health Profile</Link>
        </Button>
        <Button 
          variant="outline" 
          size="lg" 
          className="rounded-full bg-white/5 border-white/10 text-white gap-2"
          onClick={() => window.location.reload()}
        >
          <RotateCcw className="w-4 h-4" /> New Scan
        </Button>
      </div>
    </div>
  );
};

export default ResultsScreen;
